## It will create a container from centos:latest image unless set here, and will execute following stages inside.
## centos:latest is defined by default in config.toml file.
## runner is the "aws jenkins"

variables:
  goimage: "golang:1.12.1"

## spin-up a container from this image for all tasks.
image: $goimage

## stages for ci/cd
stages:
  - lint
  - build
  - test

## Lint Stage
linter:
  stage: lint
  before_script:
    - go get -u golang.org/x/lint/golint
  script:
    - "echo '############ Starting Lint Tests ###########'"
    - golint -set_exit_status
  tags:
    - awsrunner

## Build Stage
builder:
  stage: build
  before_script:
    - cp -r . $GOPATH/src/$CI_PROJECT_NAME
    - cd $GOPATH/src/$CI_PROJECT_NAME
    - export GO111MODULE=on
  script:
    - "echo '############ Starting Compile ###########'"
    - go build *.go
  tags:
    - awsrunner

## Test Stage
tester:
  stage: test
  before_script:
    - cp -r . $GOPATH/src/$CI_PROJECT_NAME
    - cd $GOPATH/src/$CI_PROJECT_NAME
    - export GO111MODULE=on
  script:
    - "echo '############ Starting Unit Tests ###########'"
    - go test
    - "echo '############ Starting Coverage Test ###########'"
    - go test -cover -v
  tags:
    - awsrunner
